int check_if_dec(char num[]);
void dec_to_bin(int int_num);
int string_size(char num[]);
int bin_check(char num[], int size);
long int bin_to_dec(char num[]);
int oct_check(char num[]);
void dec_to_oct(long int int_num);
long int oct_to_dec(char num[]);
int hex_check(char num[]);
long int hex_to_dec(char num[]);
